### ISSUE TITLE
ADC Libraries

### ISSUE THREAD

**Issue by palmerr23** [stm32duino/Arduino_Core_STM32F4#11]
Frederic,

I've been testing the advanced ADC\DAC modes (beyond single conversion, polling) using the templates from STM32Cube_FW_F4_V1.15.0\Projects\STM324x9I_EVAL\Examples\ADC\ and \DAC\

When using these other analog routines, HAL_ADC_MspInit() etc need to be customised for each configuration.

Now I'm trying out the dual-interleaved mode, it has become clear that the code in analog.c is just an initial test.

As HAL_ADC_MspInit() needs to be customised for each configuration, I'm looking at hiding the MSP_Init functions in analog.c at the system level and moving the code up to a library. The Init functions can then be customised for each mode.

When I tried this, other functions break - like dac_stop() and pwm_stop().  I think I'll be able to leave them in analog.c

Give me a few days and I'll have something workable.

Single-Polling and Single-interrupt are working already, using pretty much standard code from the Cube libraries, next up is dual-interleaved

Richard

**Comment by palmerr23** [comment]
Frederic,

As promised, I have been working on the ADC driver, following the examples in F4 Cube.

I have "ugly" code working for software intialised polling and interrupt modes, taken from the STM example code below. Now starting on DMA and multi-ADC modes.

The programmers suggest that, after initialising ADC interrupts using the HAL driver, the LL driver should be used for servicing them.

STM32Cube_FW_F4_V1.16.0\Projects\STM32F429ZI-Nucleo\Examples_MIX\ADC\ADC_SingleConversion_TriggerSW_IT\Src\main.c : 203
```

  /* Note: Perform initial ADC conversion start using driver HAL,           */
    /*       then following ADC conversion start using driver LL.             */
    /*       (mandatory to use driver LL after the first call of              */
    /*       ADC IRQ handler, implemented with driver LL).                    */
```
When you have a moment can you add the following to the system\Drivers\STM32F4xx_HAL_Driver folder to enable the ll_adc driver.

stm32f4xx_ll_adc.c & .h
and its dependencies
stm32f4xx_ll_gpio.c & .h
stm32f4xx_ll_bus.h

I will add a standalone LL IRQ handler, with a user-level callback routine, as per the example. You can integrate it into analog.c if desired. 

Thanks, Richard

**Comment by palmerr23** [comment]
Frederic,

I've tested a number of ADC modes - polling, interrupt, DMA. 

Example files are in https://github.com/palmerr23/Black-F407VET6-cube/tree/master/examples

Currently debugging Dual Mode Interleaved  (edit: now working).

**Comment by fpistm** [comment]
Proposed to move on the new repo  [Arduino_Core_STM32](https://github.com/stm32duino/Arduino_Core_STM32) as this one is deprecated. (same code).

**Comment by palmerr23** [comment]
Frederic,  Fine by me. I'm shifting across to the new core also.

**Comment by fpistm** [comment]
This issue was moved to stm32duino/Arduino_Core_STM32#5
