### ISSUE TITLE
I2C  only works for I2C_1 on PB8/9 (wire.cpp and twi.c)

### ISSUE THREAD

**Issue by palmerr23** [stm32duino/Arduino_Core_STM32F4#5]
Low priority - code works OK for I2C_1 on PB8/9 only.
I2C_2/I2C_3 not accessible via wire.

I2C init data is hardwired into twi.c (see twi.c : 148)
->No matter what the options are set in PeripheralPins.h, the code will initialise to SCL/SDA on PB8/9

Wire.cpp  only allows I2C1 (see wire.cpp : 300)
-> only one I2C is instanced in twi.h (@ line 54)

Code needs rewriting to use PeripheralPins structures to update the g_i2c_init_info[NB_I2C_INSTANCES] data before i2c_custom_init() is called from wire.cpp:61

**Comment by ghost** [comment]
I2C will be available soon. #3

**Comment by fpistm** [comment]
Proposed to close this issue as it will be covered by #3

**Comment by fpistm** [comment]
Fix with pull request #6
